### Create user
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com"
}

### Find all users
GET http://localhost:8080/user HTTP/1.1

### Find user by id
GET http://localhost:8080/user/550e8400-e29b-41d4-a716-446655440008 HTTP/1.1

### Update user
PUT http://localhost:8080/user/550e8400-e29b-41d4-a716-446655440008 HTTP/1.1
content-type: application/json

{
  "name": "Isabela Cristina",
  "email": "isabela.cristina@example.com"
}

### Delete user
DELETE http://localhost:8080/user/550e8400-e29b-41d4-a716-446655440008 HTTP/1.1