services:
  
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - database_volume:/var/lib/mysql
      - ./migration/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./migration/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASSWORD}
    ports:
      - "5672:5672" # Port for AMQP connection
      - "15672:15672" # Port for management interface
    networks:
      - queue_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  database_volume:

networks:
  queue_network:
    driver: bridge