name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build, Test, and Create Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Set up Docker
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Ensure Make is installed
      - name: Install Make
        run: sudo apt-get install -y make

      # Run 'make deps' to ensure dependencies are installed
      - name: Install dependencies
        run: make deps

      # Run 'make build' to build the project
      - name: Build the project
        run: make build

      # Run 'make test' to execute tests
      - name: Run tests
        run: make test

      # Run 'make build-image' to build the Docker image
      - name: Build Docker image
        run: make build-image

      # Push Docker image
      # - name: Push Docker image
      #   run: |
      #     docker push v3/go-template:0.1.0
